### ISSUE TITLE
Only one measurement per device is reported with new data between polls

### ISSUE THREAD

**Issue by VarrinS** [HubitatCommunity/InfluxDB-Logger#11]
I noticed what appears to be a bug. It appears the app correctly creates a infohandleEvent for each measurement reported between polls, but it only uploads one measurement to the influx server per device between polls even if there is more than one measurement given and more than one measurement changed.

Notes from the selected log lines below: 
On poll, Device 102 was T: 71.08 P: 30.39 H: 26.0, subsequent data was T: 71.04 (changed) P: 30.39 (same) H: 26.1 (changed), but only temp was uploaded. 
On poll, device 104 was T: 51.82 P:30.38 H: 42.3, subsequent data was T: 51.82 (same) P: 30.39 (changed) H: 42.3 (same), only pressure was uploaded. 
On poll, device 106 was T: 71.6 P30.38 H: 27.1, subsequent data was T: 71.54 (changed) P: 30.38 (same) H: 27.1 (same), only temp was uploaded.

In the second and third cases, only the changed data was uploaded. But in the first case, both temp and humidity change but only temp was uploaded. This seems like a bug to me. Since all measurements were reported, I think they should all be uploaded. But at a minimum, all changed data should definitely be uploaded. Here are excerpts of the logs in order but without intervening data.

app:1292020-02-18 00:08:52.105 infopostToInfluxDB(): Posting data to InfluxDB: Host: xxxxxxx, Database: hubitat, Data: [temperature,deviceId=102,deviceName=Basement\ Bath\ Environment,groupId=<snip xxxxxx>,unit=°F value=71.04 1582002492389000000
pressure,deviceId=104,deviceName=Garage\ Environment,groupId=null,groupName=Home,hubId=1,hubName=Office\ Hub,locationId=1,locationName=Office,unit=inHg value=30.39 1582002497190000000]
app:1292020-02-18 00:08:52.101 infoWriting queued data of size 2 out
app:1292020-02-18 00:08:17.187 infohandleEvent(): Garage Environment(pressure:inHg) 30.39
dev:1042020-02-18 00:08:17.124 infoGarage Environment: Pressure is 30.39 inHg
dev:1042020-02-18 00:08:17.108 infoGarage Environment: Temperature is 51.82°F
dev:1042020-02-18 00:08:17.101 infoGarage Environment: Humidity is 42.3%
app:1292020-02-18 00:08:12.389 infohandleEvent(): Basement Bath Environment(temperature:°F) 71.04
app:1292020-02-18 00:08:12.377 infohandleEvent(): Basement Bath Environment(humidity:%) 26.1
dev:1022020-02-18 00:08:12.311 infoBasement Bath Environment: Temperature is 71.04°F
dev:1022020-02-18 00:08:12.308 infoBasement Bath Environment: Pressure is 30.39 inHg
dev:1022020-02-18 00:08:12.291 infoBasement Bath Environment: Humidity is 26.1%
app:1292020-02-18 00:06:52.133 infopostToInfluxDB(): Posting data to InfluxDB: Host: xxxxxxx, Database: hubitat, Data: [temperature,deviceId=106,deviceName=First\ Floor\ Environment,groupId=<snip xxxxxx>,unit=°F value=71.54 1582002407018000000]
app:1292020-02-18 00:06:52.130 infoWriting queued data of size 1 out
app:1292020-02-18 00:06:47.013 infohandleEvent(): First Floor Environment(temperature:°F) 71.54
dev:1062020-02-18 00:06:46.976 infoFirst Floor Environment: Pressure is 30.38 inHg
dev:1062020-02-18 00:06:46.960 infoFirst Floor Environment: Humidity is 27.1%
dev:1062020-02-18 00:06:46.956 infoFirst Floor Environment: Temperature is 71.54°F
app:1292020-02-18 00:05:54.167 infopostToInfluxDB(): Posting data to InfluxDB: Host: xxxxxxxx, Database: hubitat, Data: [temperature,deviceId=102,deviceName=Basement\ Bath\ Environment,groupId=null,groupName=Home,hubId=1,hubName=Office\ Hub,locationId=1,locationName=Office,unit=°F value=71.08 1582002321169000000
humidity,deviceId=102,deviceName=Basement\ Bath\ Environment,groupId=null,groupName=Home,hubId=1,hubName=Office\ Hub,locationId=1,locationName=Office,unit=null value=26.0 1582002329254000000
humidity,deviceId=104,deviceName=Garage\ Environment,groupId=null,groupName=Home,hubId=1,hubName=Office\ Hub,locationId=1,locationName=Office,unit=null value=42.3 1582002329281000000
humidity,deviceId=106,deviceName=First\ Floor\ Environment,groupId=null,groupName=Home,hubId=1,hubName=Office\ Hub,locationId=1,locationName=Office,unit=null value=27.1 1582002329309000000
pressure,deviceId=102,deviceName=Basement\ Bath\ Environment,groupId=null,groupName=Home,hubId=1,hubName=Office\ Hub,locationId=1,locationName=Office,unit=null value=30.39 1582002329381000000
pressure,deviceId=104,deviceName=Garage\ Environment,groupId=null,groupName=Home,hubId=1,hubName=Office\ Hub,locationId=1,locationName=Office,unit=null value=30.38 1582002329407000000
pressure,deviceId=106,deviceName=First\ Floor\ Environment,groupId=null,groupName=Home,hubId=1,hubName=Office\ Hub,locationId=1,locationName=Office,unit=null value=30.38 1582002329433000000
temperature,deviceId=102,deviceName=Basement\ Bath\ Environment,groupId=null,groupName=Home,hubId=1,hubName=Office\ Hub,locationId=1,locationName=Office,unit=null value=71.08 1582002329499000000
temperature,deviceId=104,deviceName=Garage\ Environment,groupId=null,groupName=Home,hubId=1,hubName=Office\ Hub,locationId=1,locationName=Office,unit=null value=51.82 1582002329526000000
temperature,deviceId=106,deviceName=First\ Floor\ Environment,groupId=null,groupName=Home,hubId=1,hubName=Office\ Hub,locationId=1,locationName=Office,unit=null value=71.6 1582002329551000000

**Comment by dennypage** [comment]
I am not seeing this behavior.

```
app:71 2023-01-12 13:19:50.041 info postToInfluxDB(): Posting data to InfluxDB: http://192.168.230.4:8086/write?db=hubitat, Data: [humidity,deviceId=124,deviceName=sensor\ 1,groupId=null,groupName=Home,hubId=1,hubName=main\ Hub,locationId=1,locationName=main,unit=% value=54.00 1673558345626000000 temperature,deviceId=124,deviceName=sensor\ 1,groupId=null,groupName=Home,hubId=1,hubName=main\ Hub,locationId=1,locationName=main,unit=F value=57.35 1673558345635000000]
app:71 2023-01-12 13:19:50.035 info Writing queued data of size 2 out
app:71 2023-01-12 13:19:05.635 info handleEvent(): sensor 1(temperature:F) 57.35
app:71 2023-01-12 13:19:05.625 info handleEvent(): sensor 1(humidity:%) 54.00
```

If you are still seeing this issue, please re-open and provide details about your configuration parameters such as soft poll, db write frequency, and method of device selection. Thanks.
