### ISSUE TITLE
Cannot remove device if a device's driver is changed

### ISSUE THREAD

**Issue by gurpal2000** [HubitatCommunity/InfluxDB-Logger#17]
**Problem**
Cannot remove device if a device's driver is changed

**Expectation**
A checkbox should appear allowing you to remove a device

**How to reproduce**
1. Add an existing device into logging scope
2. For the device you just added, go to its config page and change the driver to something else eg. "Basic Z-wave tool"
3. Go to the logger's config page and try to remove the device. You can't as there is no checkbox visible.
4. Go back to the device's config page and put it back to driver that was originally there. Repeat 3. You can now remove the device.

Is this expected behaviour?

thanks

**Comment by ogiewon** [comment]
Changing the device driver to one that does not implement the same _standard device capabilities_ is not supported.  So, yes, this is the expected behavior.
