### ISSUE TITLE
postToInfluxDB(): Something went wrong! Response from InfluxDB: Status: 408, Headers: null, Data: null

### ISSUE THREAD

**Issue by jGiles550** [HubitatCommunity/InfluxDB-Logger#22]
Hello!

I recently had this hubitat app working on my original ISP provided router, I then moved and changed ISPs and when I configured my system I no longer could log data from sensors to my influxDB server.

My version is influx 2.4.0

I am running into the following issue:
`postToInfluxDB(): Posting data to InfluxDB: Host: 192.168.1.160, Port: 8086, Database: hubitat_db, Data: `
`postToInfluxDB(): Something went wrong! Response from InfluxDB: Status: 408, Headers: null, Data: null`

I have done the following to troubleshoot:

- Confirmed that my influxdb 2.0 server is running
- Configured my local network to 192.168.1.1-255, subnet 255.255.255.0
- Attempted multiple different devices
- Checked the database field, username, and password in the influxDB-Logger app interface

I appreciate any suggestions on how to overcome this.

**Comment by dennypage** [comment]
Since the project didn't have InfluxDB 2 support in November 2022, I assume you were running from some fork of the project. If you are still experiencing this issue, using the current version of the code, please re-open with additional information such as your database configuration parameters.
