### ISSUE TITLE
Motion sensors 

### ISSUE THREAD

**Issue by alanroche2015** [HubitatCommunity/InfluxDB-Logger#4]
Hi,

I’ve just installed the plugin into Hubitat and while everything appears to be working the motion sensor events never appear in the InfluxDB.  Have you seen this before ? 

Thanks for the amazing work linking Hubitat to InfluxDB / Grafana fantastic to finally have dashboard. 

Alan

**Comment by dennypage** [comment]
Closing stale issue. Please re-open if needed.
