### ISSUE TITLE
Power Sources dropdown does not populate

### ISSUE THREAD

**Issue by jtp10181** [HubitatCommunity/InfluxDB-Logger#62]
Found and fixed the issue on line 126 the capability is defined wrong (has trailing s that does not belong)

Current
`    'powerSources': [ title: 'Power Sources', capability: 'powerSources', attributes: ['powerSource'] ],`

Fixed
`    'powerSources': [ title: 'Power Sources', capability: 'powerSource', attributes: ['powerSource'] ],`

**Comment by dennypage** [comment]
Thanks Jeff. Would you like to do a PR?

**Comment by jtp10181** [comment]
Sure, I will get on that tomorrow.

Update: PR Submitted https://github.com/HubitatCommunity/InfluxDB-Logger/pull/63

**Comment by jtp10181** [comment]
So is this waiting for anything from me or are you just waiting to merge it until ready for next version?

**Comment by dennypage** [comment]
Not waiting on anything from you. Just really busy, and I wanted to take a look at other PRs. I'll go ahead and kick this out.

**Comment by dennypage** [comment]
Pushed
