### ISSUE TITLE
add support for HPM

### ISSUE THREAD

**Issue by aerickson** [HubitatCommunity/InfluxDB-Logger#64]
It would be great if this app supported Hubitat Package Manager (https://hubitatpackagemanager.hubitatcommunity.com/). Info on how to add support https://hubitatpackagemanager.hubitatcommunity.com/index.html#devs.

Happy to work on a PR if you're open.

**Comment by dennypage** [comment]
https://github.com/HubitatCommunity/InfluxDB-Logger/blob/master/PackageManifest.json
