### ISSUE TITLE
fix NullPointerException

### ISSUE THREAD

**Issue by aerickson** [HubitatCommunity/InfluxDB-Logger#67]
Getting this error in the logs. Should I be concerned?

`[app:528](http://hubitat.condo/logs?tab=past&deviceId=663#)2023-10-13 12:14:14.857 AM[error](http://hubitat.condo/logs?tab=past&deviceId=663#)java.lang.NullPointerException: Cannot invoke method getDisplayName() on null object on line 367 (method updated)`

**Comment by dennypage** [comment]
Please post support questions in the forum. Thank you.

**Comment by aerickson** [comment]
Sorry if the phrasing made it seem like a support request. 

It seems like a bug. We should fix it. I've done an initial look at the source, but nothing obvious.

**Comment by dennypage** [comment]
Yes, it's a support request. Please use the forum. There are a number of people that can help you there.
