### ISSUE TITLE
Change ownership/contributors of InfluxDB-Logger repo?

### ISSUE THREAD

**Issue by ogiewon** [HubitatCommunity/InfluxDB-Logger#8]
@csteele-PD - I just noticed a few pull requests on this repo.  I don't have time to maintain it, especially since I am not using it any longer.  Perhaps one of the new contributors would be willing to take responsibility for it?  Just a thought, as I hate seeing good ideas being ignored.

**Comment by dennypage** [comment]
All the PRs are currently resolved. Looking better now.
